### ISSUE TITLE
Add support for Python 3

### ISSUE THREAD

**Issue by yumike** [gears/gears#10]

**Comment by excieve** [comment]
Is this task being in progress? If not - I'm willing to do it.
Just asking to make sure there would be no collision with someone else's work.

My plan is to start with main gears package and once it's compatible (i.e. all tests pass with Python 2.6 - 3.2 and I can build an example app that works), move on to some related external packages.

**Comment by yumike** [comment]
No, I have no plans to do it in the near future, because we don't use Python 3 for web yet. So you can do it without fear.

Also, it's cool, thanks :)

**Comment by excieve** [comment]
Great! Thanks for your reply.

**Comment by yumike** [comment]
Done in #14
