### ISSUE TITLE
Add support for slimit as js compressor

### ISSUE THREAD

**Issue by yumike** [gears/gears#2]
Add support for [slimit](http://pypi.python.org/pypi/slimit/) Python library as js compressor.

**Comment by xobb1t** [comment]
If compressor registered in Environment, but slimit not installed, what it should return? `asset.bundled_source` or raise exception?

**Comment by yumike** [comment]
It should raise an exception (Errors should never pass silently).

**Comment by yumike** [comment]
Added in 37a485007f895091cd155558ca8849e68e0b7a30
