### ISSUE TITLE
Error after upgrade to 0.7

### ISSUE THREAD

**Issue by chripede** [gears/gears#24]
I upgraded from 0.6.1 to 0.7 and changed nothing else.

The three lines starting here https://github.com/gears/gears/blob/develop/gears/environment.py#L413

```
            basename = os.path.basename(asset_attributes.path_without_suffix)
            if not fnmatch(basename, basename_pattern) and basename != 'index':
                continue
```

stops everything from working. I'm not using globs. Every require'd file causes continue to happen.

**Comment by yumike** [comment]
Hi. Can't reproduce your problem. Which Python version do you use? Which directives aren't working? Can you provide an example of broken code?

**Comment by chripede** [comment]
I'm using django-gears 0.6 on Django 1.6.3 with python 2.7.3.

My settings.py includes these gears settings:

```
PROJECT_PATH = os.path.realpath(os.path.dirname(__file__) + '/../')
STATICFILES_DIRS = (
    PROJECT_PATH + '/static',
)

GEARS_ROOT = STATIC_ROOT
GEARS_DIRS = STATICFILES_DIRS
GEARS_COMPRESSORS = {
    'text/css': 'gears.compressors.CSSMinCompressor',
}
GEARS_COMPILERS = {
    '.less': 'gears_less.LESSCompiler',
    '.hbs': 'gears_handlebars.HandlebarsCompiler',
}
GEARS_PUBLIC_ASSETS = (
    lambda path: not any(path.endswith(ext) for ext in ('.css', '.js')),
    r'^css/style\.css$',
    r'^js/script\.js$',
    r'^js/app\.js$',
    r'^js/base\.js$',
    r'^js/misc\.js$',
    r'^js/plugins\.js$',
)
```

Style.css looks like this

```
/*
 *= require jquery.noty.css
 *= require noty_theme_default.less
 *= require bootstrap-datepicker.css
 *= require select2.css
 *= require nprogress.css
 *= require morris.css
 *= require font-awesome-animation.css
 *= require social-buttons.less
 *= require custom.less
*/
```

The `absolute_path` in the mentioned function holds the correct path to jquery.noty.css, but `if not fnmatch(basename, basename_pattern) and basename != 'index':` causes it to `continue` resulting in FileNotFound

**Comment by yumike** [comment]
This is because of `.css` and `.less` extensions. They must be omitted in the directives. In your example:

```
/*
 *= require jquery.noty
 *= require noty_theme_default
 *= require bootstrap-datepicker
 *= require select2
 *= require nprogress
 *= require morris
 *= require font-awesome-animation
 *= require social-buttons
 *= require custom
*/
```

It worked previously, but with ambiguous behavior. For example, `app.styl` can be imported using `=require app.css` or `=require app.less`.

**Comment by chripede** [comment]
Aha. Somehow I managed to do exactly that for the JS scripts but not the stylesheets.

Thanks a lot for the help and a great project
